//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Report
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewCoursePeople
    {
        public int Id { get; set; }
        public int CourseId { get; set; }
        public Nullable<int> PersonId { get; set; }
        public int CourseTypeId { get; set; }
        public string CourseType { get; set; }
        public Nullable<int> CertificateTypeId { get; set; }
        public string CertificateType { get; set; }
        public System.DateTime DateStart { get; set; }
        public Nullable<System.DateTime> DateEnd { get; set; }
        public string Instructor { get; set; }
        public string Location { get; set; }
        public string Department { get; set; }
        public Nullable<int> OrganizationId { get; set; }
        public Nullable<int> Duration { get; set; }
        public Nullable<int> DurationUnitId { get; set; }
        public Nullable<int> StatusId { get; set; }
        public string Status { get; set; }
        public string TrainingDirector { get; set; }
        public string Title { get; set; }
        public bool Recurrent { get; set; }
        public Nullable<int> Interval { get; set; }
        public Nullable<int> CalanderTypeId { get; set; }
        public string No { get; set; }
        public string DurationUnit { get; set; }
        public string CalendarType { get; set; }
        public string Organization { get; set; }
        public string PID { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public Nullable<int> GroupId { get; set; }
        public string JobGroup { get; set; }
        public string JobGroupCode { get; set; }
        public string JobGroupRoot { get; set; }
        public int SexId { get; set; }
        public string NID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Name { get; set; }
        public string Mobile { get; set; }
        public string IDNo { get; set; }
        public string Sex { get; set; }
        public string Customer { get; set; }
        public string ScheduleName { get; set; }
        public int EmployeeId { get; set; }
        public Nullable<int> CoursePeopleStatusId { get; set; }
        public Nullable<System.DateTime> DateStatus { get; set; }
        public Nullable<System.DateTime> DateIssue { get; set; }
        public Nullable<System.DateTime> DateExpire { get; set; }
        public string StatusRemark { get; set; }
        public string CoursePeopleStatus { get; set; }
        public string CertificateNo { get; set; }
        public Nullable<bool> IsNotificationEnabled { get; set; }
        public Nullable<int> Mandatory { get; set; }
        public string ImgUrl { get; set; }
        public string EmployeeLocation { get; set; }
        public string SMSStatus { get; set; }
        public Nullable<System.DateTime> SMSDateSent { get; set; }
        public Nullable<long> SMSRefId { get; set; }
        public string SMSMsg { get; set; }
        public string Instructor1 { get; set; }
        public string Instructor2 { get; set; }
        public Nullable<int> Instructor2Id { get; set; }
        public Nullable<int> Instructor1Id { get; set; }
        public Nullable<bool> Continual { get; set; }
        public Nullable<bool> InActive { get; set; }
        public string JobGroupCode2 { get; set; }
        public Nullable<int> ExamResult { get; set; }
        public Nullable<System.DateTime> ExamDate { get; set; }
        public Nullable<int> Year { get; set; }
        public string ExamStatus { get; set; }
        public Nullable<System.DateTime> Date_Sign_Ins1 { get; set; }
        public Nullable<System.DateTime> Date_Sign_Ins2 { get; set; }
        public Nullable<System.DateTime> Date_Sign_Director { get; set; }
        public Nullable<System.DateTime> Date_Sign_Staff { get; set; }
        public Nullable<System.DateTime> Date_Sign_OPS { get; set; }
        public Nullable<System.DateTime> Course_Date_Sign_Ins1 { get; set; }
        public Nullable<System.DateTime> Course_Date_Sign_Ins2 { get; set; }
        public Nullable<System.DateTime> Course_Date_Sign_Director { get; set; }
        public Nullable<System.DateTime> Course_Date_Sign_Staff { get; set; }
        public Nullable<System.DateTime> Course_Date_Sign_OPS { get; set; }
        public Nullable<System.DateTime> Course_Date_Exam_Sign_Ins1 { get; set; }
        public Nullable<System.DateTime> Course_Date_Exam_Sign_Ins2 { get; set; }
        public Nullable<bool> IsSessionsSynced { get; set; }
        public Nullable<int> SessionsCount { get; set; }
        public Nullable<int> PresenceCount { get; set; }
        public Nullable<double> Presence { get; set; }
        public Nullable<int> ParentId { get; set; }
    }
}
